{
  Foo() {
    break
  }
}

// ERROR: [4,3] Not inside a loop
